version: '3.2'

services:

### Proxy container #######################################

    traefik:
        build:
          context: ./$PATH_TRAEFIK/traefik/
          dockerfile: ./Dockerfile.dev
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        
